package com.pierre.shortner.feature.links.data.repository

import com.pierre.shortner.core.room_provider.dao.LinkDao
import com.pierre.shortner.core.room_provider.entity.LinkEntity
import com.pierre.shortner.feature.links.data.datasource.LinksRemoteDataSource
import com.pierre.shortner.feature.links.data.dto.ShortenUrlDto
import com.pierre.shortner.feature.links.domain.model.Link
import com.pierre.shortner.feature.links.domain.repository.LinksRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map

class LinksRepositoryImpl(
    private val remoteDataSource: LinksRemoteDataSource,
    private val linkDao: LinkDao,
) : LinksRepository {

    override suspend fun postUrl(url: String): Result<Unit> = remoteDataSource
        .postUrl(url)
        .map { response: ShortenUrlDto ->
            linkDao.insert(response.toEntity())
        }

    override fun getAllLinks(): Flow<List<Link>> = linkDao.getAllAsFlow().map { entities ->
        entities.map { it.toDomain() }
    }

    override suspend fun deleteLink(id: Long) {
        linkDao.deleteById(id)
    }

    override suspend fun deleteAllLinks() {
        linkDao.clear()
    }

    private fun ShortenUrlDto.toEntity(): LinkEntity = LinkEntity(
        id = 0, // will be generated by room
        originalLink = linksDto.original,
        shortedLink = linksDto.short,
        alias = alias
    )

    private fun LinkEntity.toDomain(): Link = Link(
        id = id,
        originalUrl = originalLink,
        shortenedUrl = shortedLink,
        alias = alias,
    )
}
