package com.pierre.shortner.feature.links.input.data.mapper

import com.pierre.shortner.core.room_provider.entity.LinkEntity
import com.pierre.shortner.feature.links.input.data.dto.ShortenUrlDto
import kotlin.time.Clock
import kotlin.time.ExperimentalTime

@OptIn(ExperimentalTime::class)
class ShortenUrlDtoMapperImpl: ShortenUrlDtoMapper {
    override fun toEntity(dto: ShortenUrlDto): LinkEntity = dto.run {
        LinkEntity(
            id = 0, // will be generated by room
            originalLink = linksDto.original,
            shortedLink = linksDto.short,
            alias = alias,
            createdAt = Clock.System.now().toEpochMilliseconds()
        )
    }
}
